// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPnIc0W_Fd6L0Cx7AOnAOXDmRTrzJz8N4',
    appId: '1:1030333682577:web:29755b1231297495efc030',
    messagingSenderId: '1030333682577',
    projectId: 'whatsapp-app-2f5f9',
    authDomain: 'whatsapp-app-2f5f9.firebaseapp.com',
    storageBucket: 'whatsapp-app-2f5f9.firebasestorage.app',
    measurementId: 'G-BVMCLC77X9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD942d2RsGw8Vt0Nj8_iz7rGED4vZ5YYKQ',
    appId: '1:1030333682577:android:bfcf676a533c0bcdefc030',
    messagingSenderId: '1030333682577',
    projectId: 'whatsapp-app-2f5f9',
    storageBucket: 'whatsapp-app-2f5f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJUmwBrqJVf0T91tNtdleGierrcFjvHUk',
    appId: '1:1030333682577:ios:193df0d8d6ff84a6efc030',
    messagingSenderId: '1030333682577',
    projectId: 'whatsapp-app-2f5f9',
    storageBucket: 'whatsapp-app-2f5f9.firebasestorage.app',
    iosBundleId: 'com.example.whatsappCloneApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPnIc0W_Fd6L0Cx7AOnAOXDmRTrzJz8N4',
    appId: '1:1030333682577:web:4c9f4f885a0919f9efc030',
    messagingSenderId: '1030333682577',
    projectId: 'whatsapp-app-2f5f9',
    authDomain: 'whatsapp-app-2f5f9.firebaseapp.com',
    storageBucket: 'whatsapp-app-2f5f9.firebasestorage.app',
    measurementId: 'G-QLGTDKXCB5',
  );
}
